source "http://rubygems.org"

gem "rack"
gem "thin"
gem "sinatra", :require => "sinatra/base"
gem "shotgun"
gem "sinatra-contrib"
gem "emk-sinatra-url-for"
gem "data_mapper"
gem "dm-mysql-adapter"
gem 'dm-types'
gem "haml"
gem "httparty"
gem "omniauth"
gem "omniauth-twitter"
gem "rdiscount"
gem "nokogiri"
