source "http://rubygems.org"

gem "rack"
gem "sinatra", :require => "sinatra/base"
gem "sinatra-contrib"
gem "emk-sinatra-url-for"
gem "sinatra-jsonp", :require => "sinatra/jsonp"
gem "data_mapper"
gem "dm-mysql-adapter"
gem "haml"
gem "httparty"
